services:  
  node:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: testing-agent-app
    ports:
      - "4001:3000"
    working_dir: /usr/src/app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: on-failure

